### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/ajax-project#1]
## ⚙️ User can search for airport using Airport name

> ##### User will be able to find their desired airport using an autofill search input

User can search for airport using Airport name, iata identifier or icao identifier

## 📐 Functionality

> ##### User will begin to type into the search input text area. As they complete their query, results will start to show in a drop-down list. The user will select their desired airport from the drop-down list by clicking on it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/211890436-49aedb34-36ed-4031-aec0-6e847f676af5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create search input
- [ ] add search function
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
