### ISSUE TITLE
User can  view Raw Metar report for chosen airport

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/ajax-project#2]
## ⚙️User can  view Raw Metar report for chosen airport

> ##### What capability will users have when this feature is merged?

User will be able to view the raw METAR report for the airport chosen

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will type in the airport name into the search input and select the airport. Once selected the user will be taken to a new page which displays the weather stats and the raw output of the METAR report.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/211922987-aeae4c0d-6f1c-4fad-b020-553de80f773c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] take the input from search bar and send the api call to AVWX
- [ ] receive JSON response from AVWX and parse
- [ ] create dom elements and insert appropriate data
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
