### ISSUE TITLE
User can view decoded METAR report

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to select the "Decoded" tab to view the METAR report in plain english

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will select the airport from the search bar on main page. User will be taken to the information page for that airport. User can then click the 'decoded' tab on the information page to view the METAR report in plain english.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/211923865-87476963-31bb-4bec-9c86-9dd046ac94ce.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create switchable tab
- [ ] parse METAR and add information 
- [ ] create a table for cloud information 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
