### ISSUE TITLE
User is alerted by flag when conditions may be dangerous

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

IFR . MVFR, Winds above 5kts, visibility below 3nm display with red tags to alert the user of potential dangeruos weather conditions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/53235890/211925069-61ce8ca2-b6c1-4d26-a244-b7ed30faefe4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create condition to render the background of the information in desired color. Red or Green
- [ ] create DOM elements and append to the DOM in the correct place.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
